#!/usr/bin/env tsx
/**
 * Print GraphQL Queries
 * 
 * This script prints out the actual GraphQL queries being generated
 * so they can be analyzed for complexity and correctness.
 */

import {
  queryPrograms,
  queryEvents,
  queryPosts,
  queryPages,
  queryExhibits,
  queryMembers,
  queryPress,
  queryImpactReport,
  queryMetrics,
  queryMetricPeriods,
} from '../src/lib/contentful/query-builder';

// Test with sample IDs for id_in queries
const sampleIDs = ['id1', 'id2', 'id3', 'id4', 'id5'];

console.log('='.repeat(80));
console.log('GraphQL Queries Generated by Query Builder');
console.log('='.repeat(80));
console.log();

console.log('1. queryEvents({ limit: 100 })');
console.log('-'.repeat(80));
console.log(queryEvents({ limit: 100 }));
console.log();

console.log('2. queryEvents() - no limit');
console.log('-'.repeat(80));
console.log(queryEvents());
console.log();

console.log('3. queryPrograms({ where: "url_exists: true", limit: 100 })');
console.log('-'.repeat(80));
console.log(queryPrograms({ where: 'url_exists: true', limit: 100 }));
console.log();

console.log('4. queryExhibits({ limit: 100 })');
console.log('-'.repeat(80));
console.log(queryExhibits({ limit: 100 }));
console.log();

console.log('5. queryMembers({ limit: 100 })');
console.log('-'.repeat(80));
console.log(queryMembers({ limit: 100 }));
console.log();

console.log('6. queryPress({ limit: 100 })');
console.log('-'.repeat(80));
console.log(queryPress({ limit: 100 }));
console.log();

console.log('7. queryPosts({ where: "contentfulMetadata: { tags: { id_contains_some: [\\"blog\\"] } }", limit: 100 })');
console.log('-'.repeat(80));
console.log(queryPosts({ where: 'contentfulMetadata: { tags: { id_contains_some: ["blog"] } }', limit: 100 }));
console.log();

console.log('8. queryPosts({ where: "contentfulMetadata: { tags: { id_contains_some: [\\"topicHistory\\"] } }", limit: 100 })');
console.log('-'.repeat(80));
console.log(queryPosts({ where: 'contentfulMetadata: { tags: { id_contains_some: ["topicHistory"] } }', limit: 100 }));
console.log();

console.log('9. queryPages({ where: "sys: { id: \\"test-id\\" }", limit: 1 })');
console.log('-'.repeat(80));
console.log(queryPages({ where: 'sys: { id: "test-id" }', limit: 1 }));
console.log();

console.log('10. queryPrograms({ where: "sys: { id: \\"test-id\\" }", limit: 1 })');
console.log('-'.repeat(80));
console.log(queryPrograms({ where: 'sys: { id: "test-id" }', limit: 1 }));
console.log();

console.log('='.repeat(80));
console.log('Query Analysis Complete');
console.log('='.repeat(80));

