import requests
import json
import os
import asyncio

ABSOLUTE_MADE_DIR = os.path.dirname(
    os.path.realpath(__file__)
) + "/.."

output = os.path.join(ABSOLUTE_MADE_DIR, '.staging/eventbrite_events.json')

with open(
    os.path.join(ABSOLUTE_MADE_DIR, '.keys/eventbrite.json'), 'r') as file:
    data = json.load(file)

PERSONAL_OAUTH_TOKEN = data['eventbrite']['api_key']

HEADERS = {
    'Content-Type': 'application/json',  # Set the content type to JSON if you are sending JSON data
    'Authorization': f'Bearer {PERSONAL_OAUTH_TOKEN}'  # Include an authorization token if required
}

payloads = [
    {
        "event": {
            "event": {
                "name": {
                    "html": "<p>MADE Classroom: TEST ATTEMPT</p>"
                },
                "summary": "This is the made classroom",
                "start": {
                    "timezone": "America/Los_Angeles",
                    "utc": "2024-09-14T16:30:00Z"
                },
                "end": {
                    "timezone": "America/Los_Angeles",
                    "utc": "2024-09-14T18:00:00Z"
                },
                "currency": "USD",
                "capacity": 20,
            }
        },
        "description": {
            "hide_virtual_venue_content": False,
            "has_autogenerated_content": False,
            "modules":[
                {
                    "type":"text",
                    "data":{
                        "body":{
                            "type":"text",
                            "text":"<p>thing</p>",
                            "alignment": "left"
                        }
                    }
                }
            ],
            "publish": True,
            "purpose": "listing"
        }
    }
]

class EventbriteDescription:
    """
    A class that handles the description of an event on Eventbrite.
    """

    def __init__(self, organization_id):
        self.organization_id = organization_id

    def new(self, event_id, payload, version_number):
        """
        Creates a new description for the specified event.

        Args:
            event_id (str): The ID of the event.
            payload (dict): The payload containing the description data.
            version_number (int): The version number of the description.

        Returns:
            None
        """
        url = f'https://www.eventbriteapi.com/v3/events/{event_id}/structured_content'
        desc_url = os.path.join(url, f'{version_number}')
        print(desc_url)
        response = requests.post(
            desc_url,
            headers=HEADERS,
            json=payload.get('description')
        )
        # Check the response
        if response.status_code == 200:
            print('Success Set Modules:', response.json())
            self.show(event_id)
        else:
            print('Failed:', response.status_code, response.text)

    def show(self, event_id):
        """
        Retrieves and displays the description of the specified event.

        Args:
            event_id (str): The ID of the event.

        Returns:
            None
        """
        url = f'https://www.eventbriteapi.com/v3/events/{event_id}/structured_content'
        response = requests.get(
            url,
            headers=HEADERS
        )
        # Check the response
        if response.status_code == 200:
            print('Success Show Modules:', response.json())
        else:
            print('Failed:', response.status_code, response.text)

class EventbriteEvents:
    """
    A class representing Eventbrite events.

    Attributes:
        organization_id (str): The ID of the organization.
        url (str): The URL for Eventbrite API.

    Methods:
        post_structure(payload, event_result): Posts the structure of the event.
        new(payload): Creates a new event.
        copy(event_id, payload): Copies an existing event.
        get(event_id): Retrieves information about an event.
        show_all(page): Retrieves all events.
        show(page): Retrieves events on a specific page.
        structure(event_id): Retrieves the structure of an event.
        publish(event_id): Publishes an event.
    
    Example:
    ---------
    eventbrite = EventbriteOrganizations()
    organization_id = eventbrite.request()
    event = EventbriteEvents(organization_id)
    """

    def __init__(self, organization_id):
        self.organization_id = organization_id
        self.url = f'https://www.eventbriteapi.com/v3/organizations/{organization_id}/events/'
        # print(organization_id)

    
    def post_structure(self, payload, event_result):
        """
        Attempt to add in a description to an event in the form of structured content. Currently should work, but Eventbrite API is broken.

        Args:
            payload (dict): The payload containing the structure of the event.
            event_result (dict): The result of creating the event.

        Returns:
            None
        """
        description = EventbriteDescription(self.organization_id, 1)
        event_id = event_result['id']
        description.new(event_id, payload)

    def new(self, payload):
        """
        Creates a new event.

        Args:
            payload (dict): The payload containing the details of the event.

        Returns:
            None
        """
        response = requests.post(
            self.url,
            headers=HEADERS,
            json=payload
        )
        if response.status_code == 200:
            print('Success:', response.json())
            # Don't attempt to add structured content, as API is broken. Keep here for reference.
            # self.post_structure(payload, response.json())
        else:
            print('Failed:', response.status_code, response.text)

    def copy(self, event_id, payload):
        """
        Copies an existing event.

        Args:
            event_id (str): The ID of the event to be copied.
            payload (dict): The payload containing the details of the copied event.

        Returns:
            None
        """
        url = f'https://www.eventbriteapi.com/v3/events/{event_id}/copy/'
        response = requests.post(
            url,
            headers=HEADERS,
            json=payload
        )
        if response.status_code == 200:
            print('Success:', response.json())
        else:
            print('Failed:', response.status_code, response.text)
    
    async def get(self, event_id):
        """
        Retrieves information about an event.

        Args:
            event_id (str): The ID of the event.

        Returns:
            dict: The JSON response containing the event information.
        """
        url = f'https://www.eventbriteapi.com/v3/events/{event_id}/'
        response = requests.get(
            url,
            headers=HEADERS
        )
        # Check the response
        if response.status_code == 200:
            return response.json()
            # print('Success:', response.json())
        else:
            print('Failed:', response.status_code, response.text)
            return response.text
        
    async def show_all(self, page=None):
        """
        Retrieves all events.

        Args:
            page (int): The page number of the events to retrieve. Defaults to None.

        Returns:
            list: A list of JSON responses containing the events.
        """
        response = requests.get(
            self.url,
            headers=HEADERS,
            params={ "page": 1 if page is None else page }
        )
        all = []
        if response.status_code == 200:
            if page != response.json()["pagination"]["page_count"]:
                result = await self.show(response.json()["pagination"]["page_number"] + 1)
                return all + [result]
            else:
                return all + [response.json()]
        else:
            print('Failed:', response.status_code, response.text)
            return None

    async def show(self, page=None):
        """
        Retrieves events on a specific page.

        Args:
            page (int): The page number of the events to retrieve. Defaults to None.

        Returns:
            str: The JSON response containing the events.

        Example:
        --------
        eventbrite = EventbriteEvents(organization_id)
        out1 = await eventbrite.show(page=2)
        out2 = await eventbrite.show(page=3)
        """
        response = requests.get(
            self.url,
            headers=HEADERS,
            params={ "page": 1 if page is None else page }
        )
        # Check the response
        if response.status_code == 200:
            if page is None:
                print("---------- jumping to next page number")
                return await self.show(response.json()["pagination"]["page_count"])
            else:
                return json.dumps(response.json(), indent=4)
        else:
            print('Failed:', response.status_code, response.text)
            return None
    
    def structure(self, event_id):
        """
        Retrieves the structure of an event.

        Args:
            event_id (str): The ID of the event.

        Returns:
            None
        """
        url = f'https://www.eventbriteapi.com/v3/events/{event_id}/structured_content'
        response = requests.get(
            url,
            headers=HEADERS
        )
        # Check the response
        if response.status_code == 200:
            print('Success:', response.json())
        else:
            print('Failed:', response.status_code, response.text)
    
    def publish(self, event_id):
        """
        Publishes an event.

        Args:
            event_id (str): The ID of the event to be published.

        Returns:
            None
        """
        url = f'https://www.eventbriteapi.com/v3/events/{event_id}/publish'
        response = requests.post(
            url,
            headers=HEADERS
        )
        # Check the response
        if response.status_code == 200:
            print('Success:', response.json())
        else:
            print('Failed:', response.status_code, response.text)

class EventbriteOrganizations:
    """
    Represents a class for interacting with Eventbrite organizations.

    Example:
    ---------
    media = EventsMedia()
    media.request()
    """

    url = 'https://www.eventbriteapi.com/v3/users/me/organizations'
    headers = {
        'Content-Type': 'application/json',  # Set the content type to JSON if you are sending JSON data
        'Authorization': f'Bearer {PERSONAL_OAUTH_TOKEN}'
    }

    def request(self):
        """
        Sends a GET request to the Eventbrite API to retrieve the organizations associated with the user.

        Returns:
            str: The ID of the first organization in the response, or None if the request fails.
        """
        response = requests.get(self.url, headers=self.headers)
        if response.status_code == 200:
            organizations = response.json()['organizations']
            # print(organizations)
            return organizations[0]['id']
        else:
            print('Failed:', response.status_code, response.text)
            return None

class EventsDataManager:
    def __init__(self):
        pass

    def create(self):
        pass

class EventsMedia:
    """
    Represents a class for handling Eventbrite media requests.
    """

    def __init__(self):
        self.url = "https://www.eventbriteapi.com/v3/media"
        self.headers = {
            'Content-Type': 'application/json',  # Set the content type to JSON if you are sending JSON data
            'Authorization': f'Bearer {PERSONAL_OAUTH_TOKEN}'
        }
    
    def request(self):
        """
        Sends a GET request to the Eventbrite media API endpoint and prints the response.

        Returns:
            None: If the request fails.
        """
        response = requests.get(self.url, headers=self.headers)
        if response.status_code == 200:
            print('Success:', response.json())
        else:
            print('Failed:', response.status_code, response.text)
            return None

async def main():
    eventbrite = EventbriteOrganizations()
    organization_id = eventbrite.request()

    event = EventbriteEvents(organization_id)
    out = await event.show_all(page=2)
    arr = []

    for o in out:
        j = json.loads(o)
        arr.append(j)
    with open(output, 'w') as outfile:
        json.dump(arr, outfile, indent=4)

if __name__ == "__main__":
    # main()
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
